# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
  env:
    MYSECRET: "bilgmn6ily2wlblmx2zgtasdpu2cds5wv2uogyyjy7gna2likyfq"
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'

- bash: |
    echo $MYSECRET
    
- bash: |
    git push --prune https://$MYSECRET@dev.azure.com/$A_LittleBigPlanetRepository \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Azure'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
